language: go
go:
  - 1.x
notificaitons:
  email:
    recipients: 68298506@qq.com
    on_failure: always  
install:
  - go get -u github.com/dave/courtney
  - go get -t -v ./...
script:
  - courtney
after_success:
  - bash <(curl -s https://codecov.io/bash)
